version: '3.1'

services:

  datalytics-db:
    image: postgres:latest
    restart: always
    container_name: datalytics-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}"
    networks:
      - postgres


networks:
  postgres:
    driver: bridge

volumes:
    pgadmin:
    postgres: